/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.CodeComplexityCalculator;

import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Imali
 */

  

public class InheritanceResultScreen extends javax.swing.JFrame {

    ArrayList<Integer> ClassesCount = new ArrayList<Integer>();
     ArrayList<Integer> Ti = new ArrayList<Integer>();
      ArrayList<Integer> Ci = new ArrayList<Integer>();
      
      ArrayList<String> classes = new ArrayList<String>();
     ArrayList<Integer> DirectInheritence = new ArrayList<Integer>();
      ArrayList<Integer> IndirectInheritence = new ArrayList<Integer>();
      
      int index1 , index2 , index3 , index4 , index5;

    public InheritanceResultScreen( int index1 , int index2 , int index3 , int index4 , int index5 , ArrayList<String> classes , ArrayList<Integer> directInheritence ,  ArrayList<Integer> IndirectInheritence) {
          initComponents();
          this.classes = classes ;
          this.DirectInheritence = directInheritence;
          this.IndirectInheritence = IndirectInheritence;
          
        DefaultTableModel table = (DefaultTableModel) resultTable.getModel();
         
         for( int x = 0 ; x < classes.size() ; x++) {
             ClassesCount.add(x+1);
         }
         table.addColumn("Count" ,ClassesCount.toArray());
         table.addColumn("Class" ,classes.toArray());
         table.addColumn("DirectInheritence" ,directInheritence.toArray());
         table.addColumn("IndirectInheritence" ,IndirectInheritence.toArray());
         
         for(int y = 0 ; y < classes.size() ; y++) {
            Ti.add(directInheritence.get(y) + IndirectInheritence.get(y));
        }
         table.addColumn("Ti" ,Ti.toArray());
        for(int h = 0 ; h < classes.size() ; h++) {
           if(Ti.get(h) == 0) {
               Ci.add(Ti.get(h) * index1);
           }
            if(Ti.get(h) == 1) {
               Ci.add(Ti.get(h) * index2);
           }
             if(Ti.get(h) == 2) {
               Ci.add(Ti.get(h) * index3);
           }
              if(Ti.get(h) == 3) {
               Ci.add(Ti.get(h) * index4);
           }
            if(Ti.get(h) >= 4) {
               Ci.add(Ti.get(h) *index5);
           }
        }
         table.addColumn("Ci" ,Ti.toArray());
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Code Complexity Calculator");
        setName("InheritedResultScreen"); // NOI18N

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(resultTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Change Allocated Values for Weights");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Complexity of a Program Statement due to Inheritance ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainScreen nextScreen = new MainScreen();
        nextScreen.setVisible(true);

        this.dispose();//to close the current jframe 
    }//GEN-LAST:event_jButton1ActionPerformed

    //Weight Button
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        InheritanceWeights iw = new InheritanceWeights(classes , DirectInheritence , IndirectInheritence );
        iw.setVisible(true);
        this.dispose();
      
    }//GEN-LAST:event_jButton3ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTable resultTable;
    // End of variables declaration//GEN-END:variables
}
